### PR TITLE
Add just_owner access strategy

### PR DESCRIPTION
**Pull request by debian-sh**
I don't have possibilities to test because requires in many modules are broken.

### CODE REVIEW

**Comment by groovy354** [comment]
Which requires are broken in your opinion? And what are the symptoms of that?

**Comment by debian-sh** [comment]
I will show you this tomorrow.

**Comment by groovy354** [comment]
Ok

**Comment by debian-sh** [comment]
I think you can merge it. My problem isn't associated this feature.

**Pull request merged**
